rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: test-producer-group
server:
  port: 8088
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seata_order?allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    show-sql: true