server:
  port: 9091

spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seata_order?allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: root

seata:
  application-id: order-service
  tx-service-group: order-service-seata-group
  service:
    vgroup-mapping:
      order-service-seata-group: default
    grouplist:
      default: 127.0.0.1:8091